FROM node:19-alpine

ENV ENV production

WORKDIR /usr/src/app

COPY ./package.json ./
COPY ./package-lock.json ./

RUN apk add --no-cache bash \
 && npm install \
 && npm cache clean --force

COPY ./ .

RUN npm run build:ui

CMD ["npm", "run", "start"]
